export const CREATE_FEEDBACK = "CREATE_FEEDBACK";
export const LOAD_FEEDBACK = "LOAD_FEEDBACK";

export const CREATE_SLIDE = "CREATE_SLIDE";
export const CHANGE_SLIDE = "CHANGE_SLIDE";
export const CLEAR_SLIDES = "CLEAR_SLIDES";
export const SET_RIGHT = "SET_RIGHT";
export const SET_LEFT = "SET_LEFT";
export const SET_CURRENT_SLIDER = "SET_CURRENT_SLIDER";
export const CLEAR_CURRENT_SLIDER = "CLEAR_CURRENT_SLIDER";

export const CLOSE_MODAL = "CLOSE_MODAL";
export const OPEN_MODAL = "OPEN_MODAL";
export const MODAL_ONCHANGE_DESCRIPTION = "MODAL_ONCHANGE_DESCRIPTION";
export const MODAL_ONCHANGE_TITLE = "MODAL_ONCHANGE_TITLE";
export const SET_MODAL_CONTENT = "SET_MODAL_CONTENT";
export const SET_TITLE_ERROR = "SET_TITLE_ERROR";
export const SET_DESCRIPTION_ERROR = "SET_DESCRIPTION_ERROR";
export const SET_MODAL_DISABLE = "SET_MODAL_DISABLE";
export const SET_MODAL_SUCCESS = "SET_MODAL_SUCCESS";

export const UPLOAD_FILE = "UPLOAD_FILE";
export const UPLOAD_SUCCESS = "UPLOAD_SUCCESS";
export const UPLOAD_FAILURE = "UPLOAD_FAILURE";
export const FILE_IS_LOADING = "FILE_IS_LOADING";
export const CLEAR_FILE = "CLEAR_FILE";
